### PR TITLE
Admin Panel : refactor and model added

### PR DESCRIPTION
**Pull request by LeandervanAarde26**
## Description 
Model has been added for projects and relationship created between user and Project(https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html)

db connection has been altered and thus env has changed.

### CODE REVIEW

**Review by CydoEntis — CHANGES_REQUESTED** [review]
.flaskenv never gets uploaded to the git repo, it is kept locally or on the server to hide your credentials.

**Review by CydoEntis — CHANGES_REQUESTED** [review]
Projects are basically jobs that the freelancer has accepted from a client.

- project_name: just call it name... the table itself is projects already
- starting_at??? - start_date (The date the project was started)
- ending_at??? - end_date (The date the project should be completed)
- Missing the foreign key to map the user id to the project...

- Not sure if projects needs to be of type List.

**Review by CydoEntis — APPROVED** [review]

**Comment by LeandervanAarde26** [comment]
LGTM

**Review by CydoEntis — COMMENTED** [review]
Good?

**Review by CydoEntis — COMMENTED** [review]
Good.

**Pull request merged**
